### ISSUE TITLE
This package should use a better package name

### ISSUE THREAD

**Issue by panlatent** [yiisoft/aliases#19]
This package should use a better package name：

Use `paths` instead of `aliases`

Usually, we use this package on the path (file address, URL...), use'paths' to better express its function, and the alias is just a function under this package. 

Using paths as a package name will facilitate the expansion of related functions in the future, not just aliases.

...

`Yiisoft\Aliases\Aliases` is ugly, while `Yiisoft\Paths\Aliases` may be more beautiful.

**Comment by samdark** [comment]
That's not only about paths. URL could be aliased as well.

**Comment by samdark** [comment]
It's also a bit too late to change the name since 1.0.0 was tagged...

**Comment by panlatent** [comment]
Changing the name of a package that has already been released does cause some problems, but I think it's not too late before the official release of Yii 3.0. For package names, I think paths are also accurate for URLs. In the Yii project, we use aliases to describe file system paths or URLs. We usually don't abuse aliases for other purposes. Using `paths' or others can limit this function to a suitable scenario.

So, if it can be changed, I think it can be discussed in the community. Maybe keeping the current package and supporting a new `paths` package is a good choice? But we must first determine whether `paths` is reasonable and accepted.

**Comment by samdark** [comment]
There's a part of URL called "path". May be confusing.

**Comment by roxblnfk** [comment]
> There's a part of URL called "path". May be confusing.

i think this is the argument for renaming

**Comment by samdark** [comment]
No, That's not for renaming. For example, we may define `@paymentApi` alias with a value of `https://example.com/api/payment`. That value consists of protocol, domain, path.

**Comment by panlatent** [comment]
> URL中有一部分称为“路径”。可能会造成混乱。

From the user's perspective, our usage of the getAlias method is to generate a'path', whether it is a file system path or a URL. The implicit meaning of'path' is a string separated by slashes. For the setAlias method, we usually set the file path prefix or the Schema and Host parts (including part of the Path) in the URL, which implicitly indicates that alias is used to process the path.

This is the reason I thought of. The package name was changed to make Yii 3 more expressive.

**Comment by samdark** [comment]
Thought about it. The proposal isn't bad per se but has its cons:

1. Mental collision with URL's path.
2. The need to change already tagged package.
3. Possible double meaning, confusion with something that works with file system.

As a result, I think the name should be left as is. Thanks for proposal though, you're very welcome to participate in Yii 3.
