### ISSUE TITLE
Can't set alias like /

### ISSUE THREAD

**Issue by g-rodigy** [yiisoft/aliases#67]
### What steps will reproduce the problem?
````php
use Yiisoft\Aliases\Aliases;

$aliases = new Aliases();
$aliases->set('@url', '/');

echo $aliases->get('@url');
````

>Any trailing / and \ characters in the given path will be trimmed.

So it is not ending slash, slash is a path. Maybe need add exclusion for this case?

### What is the expected result?
/
### What do you get instead?
empty string

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.0
| PHP version      | 8.0
| Operating system |

https://github.com/yiisoft/aliases/blob/2ed5e38d6ac503ec4c1af39115361097b6449135/src/Aliases.php#L70-L72

**Comment by vjik** [comment]
Should we prepare aliases on set?
Now aliases trim slashes on set.

**Comment by cebe** [comment]
Solution here would be to check if the $path contains only `/` and keep it in that case.

```
$aliases = new Aliases();
$aliases->set('@url', '/');
$aliases->get('@url'); // should return '/'
$aliases->get('@url/somepath'); // should return '/somepath'
```

The last one already works as far as I see, only the edge case must be fixed.

**Comment by niqingyang** [comment]
What's the current status of this issue? I also encountered the same problem. When using yiisoft/assets, the aliases @baseUrl and @assetsUrl I set were all "/", but now they have become "", causing the page's js, css, and image links to be wrong. , from the absolute path to a relative path. Can you provide some additional configuration options to let the user decide how to handle "/" or is there a better way?

**Comment by vjik** [comment]
One of main goals of usage aliases — concatenate resolved alias with path (`$aliases->get('@url') . "/somepath"`). So we decide always trim slash. For `/` also.
