### ISSUE TITLE
Add support of backslash

### ISSUE THREAD

**Issue by vjik** [yiisoft/aliases#68]
This code throws error:

```php
$aliases->set('@yii', 'path');
$aliases->get('@yii\\framework');
```

Error: `InvalidArgumentException: Invalid path alias: @yii\framework`

Need add support of backslash or full remove work with backslashes, becuse now backslashes are trim in several places.

**Comment by cebe** [comment]
> Need add support of backslash or full remove work with backslashes, becuse now backslashes are trim in several places.

Backslashes are only trimmed in paths, they are not allowed in aliases.

We have two different types of data here:

1. Alias = String that begins with `@` and is a _pointer_ to some path or URL, the Path separator is `/` so it is platform independent and we do not have multiple representations of the same alias.
2. Path/URL = platform or environment specific string that you get when you resolve the Alias (_pointer_)

Aliases is a mapping of virtual paths to real paths or urls. Having two different representations of the same pointer in a mapping makes the mapping harder to understand and can cause more bugs. When there is a mapping from a key to a value a key should only exist once and have a clear representation.
